/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeoChecklistRouteImport } from './routes/seo-checklist'
import { Route as QrWifiRouteImport } from './routes/qr-wifi'
import { Route as QrWhatsappRouteImport } from './routes/qr-whatsapp'
import { Route as QrVcardRouteImport } from './routes/qr-vcard'
import { Route as QrMenuRestoranRouteImport } from './routes/qr-menu-restoran'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoChecklistRoute = SeoChecklistRouteImport.update({
  id: '/seo-checklist',
  path: '/seo-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const QrWifiRoute = QrWifiRouteImport.update({
  id: '/qr-wifi',
  path: '/qr-wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const QrWhatsappRoute = QrWhatsappRouteImport.update({
  id: '/qr-whatsapp',
  path: '/qr-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const QrVcardRoute = QrVcardRouteImport.update({
  id: '/qr-vcard',
  path: '/qr-vcard',
  getParentRoute: () => rootRouteImport,
} as any)
const QrMenuRestoranRoute = QrMenuRestoranRouteImport.update({
  id: '/qr-menu-restoran',
  path: '/qr-menu-restoran',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qr-menu-restoran': typeof QrMenuRestoranRoute
  '/qr-vcard': typeof QrVcardRoute
  '/qr-whatsapp': typeof QrWhatsappRoute
  '/qr-wifi': typeof QrWifiRoute
  '/seo-checklist': typeof SeoChecklistRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qr-menu-restoran': typeof QrMenuRestoranRoute
  '/qr-vcard': typeof QrVcardRoute
  '/qr-whatsapp': typeof QrWhatsappRoute
  '/qr-wifi': typeof QrWifiRoute
  '/seo-checklist': typeof SeoChecklistRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/qr-menu-restoran': typeof QrMenuRestoranRoute
  '/qr-vcard': typeof QrVcardRoute
  '/qr-whatsapp': typeof QrWhatsappRoute
  '/qr-wifi': typeof QrWifiRoute
  '/seo-checklist': typeof SeoChecklistRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/qr-menu-restoran'
    | '/qr-vcard'
    | '/qr-whatsapp'
    | '/qr-wifi'
    | '/seo-checklist'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/qr-menu-restoran'
    | '/qr-vcard'
    | '/qr-whatsapp'
    | '/qr-wifi'
    | '/seo-checklist'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/qr-menu-restoran'
    | '/qr-vcard'
    | '/qr-whatsapp'
    | '/qr-wifi'
    | '/seo-checklist'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QrMenuRestoranRoute: typeof QrMenuRestoranRoute
  QrVcardRoute: typeof QrVcardRoute
  QrWhatsappRoute: typeof QrWhatsappRoute
  QrWifiRoute: typeof QrWifiRoute
  SeoChecklistRoute: typeof SeoChecklistRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-checklist': {
      id: '/seo-checklist'
      path: '/seo-checklist'
      fullPath: '/seo-checklist'
      preLoaderRoute: typeof SeoChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-wifi': {
      id: '/qr-wifi'
      path: '/qr-wifi'
      fullPath: '/qr-wifi'
      preLoaderRoute: typeof QrWifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-whatsapp': {
      id: '/qr-whatsapp'
      path: '/qr-whatsapp'
      fullPath: '/qr-whatsapp'
      preLoaderRoute: typeof QrWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-vcard': {
      id: '/qr-vcard'
      path: '/qr-vcard'
      fullPath: '/qr-vcard'
      preLoaderRoute: typeof QrVcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-menu-restoran': {
      id: '/qr-menu-restoran'
      path: '/qr-menu-restoran'
      fullPath: '/qr-menu-restoran'
      preLoaderRoute: typeof QrMenuRestoranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QrMenuRestoranRoute: QrMenuRestoranRoute,
  QrVcardRoute: QrVcardRoute,
  QrWhatsappRoute: QrWhatsappRoute,
  QrWifiRoute: QrWifiRoute,
  SeoChecklistRoute: SeoChecklistRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
